# Generated by Django 5.2.15 on 2026-06-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='プロジェクト名')),
                ('folder_name', models.CharField(max_length=255, unique=True, verbose_name='フォルダ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_active', models.BooleanField(default=False, verbose_name='アクティブ')),
                ('auto_image_count', models.IntegerField(default=0, verbose_name='自動取得画像数')),
                ('manual_image_count', models.IntegerField(default=0, verbose_name='手動取得画像数')),
            ],
            options={
                'verbose_name': 'データ収集プロジェクト',
                'verbose_name_plural': 'データ収集プロジェクト',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCollectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255, verbose_name='セッション名')),
                ('collection_type', models.CharField(choices=[('auto', '自動'), ('manual', '手動')], max_length=10, verbose_name='収集タイプ')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='終了時間')),
                ('image_count', models.IntegerField(default=0, verbose_name='収集画像数')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='get_imgs.datacollectionproject', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'データ収集セッション',
                'verbose_name_plural': 'データ収集セッション',
                'ordering': ['-start_time'],
            },
        ),
    ]
