# Generated by Django 5.2.15 on 2026-06-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotator', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, verbose_name='モデル名')),
                ('result_image_path', models.CharField(max_length=512, verbose_name='推論結果画像パス')),
                ('image_width', models.PositiveIntegerField(verbose_name='画像幅')),
                ('image_height', models.PositiveIntegerField(verbose_name='画像高さ')),
                ('detected_class_summary', models.JSONField(help_text='クラス名とカウントの辞書', verbose_name='検出クラス要約')),
                ('total_objects_count', models.PositiveIntegerField(default=0, verbose_name='総検出オブジェクト数')),
                ('inference_config', models.JSONField(blank=True, default=dict, verbose_name='推論設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='レコード作成日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_results', to='annotator.project', verbose_name='プロジェクト')),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_results', to='training.trainingrun', verbose_name='学習モデル')),
            ],
            options={
                'verbose_name': '推論結果',
                'verbose_name_plural': '推論結果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.PositiveIntegerField(verbose_name='クラスID')),
                ('class_name', models.CharField(max_length=100, verbose_name='クラス名')),
                ('confidence', models.FloatField(verbose_name='信頼度')),
                ('bbox_center_x', models.FloatField(help_text='バウンディングボックス中央のX座標（元画像に対する割合）', verbose_name='中央X座標')),
                ('bbox_center_y', models.FloatField(help_text='バウンディングボックス中央のY座標（元画像に対する割合）', verbose_name='中央Y座標')),
                ('bbox_width', models.FloatField(help_text='バウンディングボックスの幅（元画像に対する割合）', verbose_name='幅')),
                ('bbox_height', models.FloatField(help_text='バウンディングボックスの高さ（元画像に対する割合）', verbose_name='高さ')),
                ('inference_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='checker.inferenceresult', verbose_name='推論結果')),
            ],
            options={
                'verbose_name': '検出オブジェクト',
                'verbose_name_plural': '検出オブジェクト',
                'ordering': ['-confidence'],
            },
        ),
    ]
