# Generated by Django 5.2.15 on 2026-06-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flipud', models.FloatField(blank=True, default=0.0, help_text='上下反転確率 (flipud)')),
                ('fliplr', models.FloatField(blank=True, default=0.5, help_text='左右反転確率 (fliplr)')),
                ('mixup', models.FloatField(blank=True, default=0.0, help_text='MixUp合成率 (mixup)')),
                ('perspective', models.FloatField(blank=True, default=0.0, help_text='遠近変換強度 (perspective)')),
                ('shear', models.FloatField(blank=True, default=0.0, help_text='シアー強度 (shear)')),
                ('scale', models.FloatField(blank=True, default=0.5, help_text='スケール変換範囲 (scale)')),
                ('training_name', models.CharField(help_text='デフォルト: プロジェクト名_学習年月日_時分秒', max_length=255, verbose_name='学習名')),
                ('data_type', models.CharField(choices=[('data_collection', 'data_collection'), ('cropped', 'cropped')], max_length=32)),
                ('dataset_yaml', models.CharField(max_length=512)),
                ('model_name', models.CharField(max_length=255)),
                ('epochs', models.PositiveIntegerField(default=100)),
                ('imgsz', models.CharField(default='640', max_length=32)),
                ('batch', models.PositiveIntegerField(default=16)),
                ('other_params', models.JSONField(blank=True, default=dict)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('saved_model_path', models.CharField(blank=True, max_length=512)),
                ('config_yaml_path', models.CharField(blank=True, help_text='設定用YAMLファイルのパス（推論・検出共通）', max_length=512)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False, help_text='現在アクティブな学習モデル')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='annotator.project', verbose_name='プロジェクト')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project',), name='unique_active_training_per_project')],
                'unique_together': {('project', 'training_name')},
            },
        ),
    ]
