# Generated by Django 5.2.15 on 2026-06-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255, verbose_name='画像ファイル名')),
                ('original_path', models.TextField(verbose_name='元画像パス')),
                ('width', models.IntegerField(default=0, verbose_name='幅')),
                ('height', models.IntegerField(default=0, verbose_name='高さ')),
                ('is_processed', models.BooleanField(default=False, verbose_name='処理済み')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '切り取り画像',
                'verbose_name_plural': '切り取り画像',
                'ordering': ['image_name'],
            },
        ),
        migrations.CreateModel(
            name='CropArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='X座標')),
                ('y', models.IntegerField(verbose_name='Y座標')),
                ('width', models.IntegerField(verbose_name='幅')),
                ('height', models.IntegerField(verbose_name='高さ')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='ラベル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('cropped_image_path', models.CharField(blank=True, max_length=500, verbose_name='切り取り後画像パス')),
                ('confidence', models.FloatField(default=1.0, verbose_name='信頼度')),
                ('crop_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_areas', to='crop_app.cropimage', verbose_name='対象画像')),
            ],
            options={
                'verbose_name': '切り取り領域',
                'verbose_name_plural': '切り取り領域',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='総セッション数')),
                ('completed_sessions', models.IntegerField(default=0, verbose_name='完了セッション数')),
                ('total_images', models.IntegerField(default=0, verbose_name='総画像数')),
                ('processed_images', models.IntegerField(default=0, verbose_name='処理済み画像数')),
                ('total_crop_areas', models.IntegerField(default=0, verbose_name='総切り取り領域数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crop_app_progress', to='annotator.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '切り取り進捗',
                'verbose_name_plural': '切り取り進捗',
            },
        ),
        migrations.CreateModel(
            name='CropSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200, verbose_name='セッション名')),
                ('source_folder', models.CharField(choices=[('auto', '自動収集画像'), ('manual', '手動収集画像'), ('annotation', 'アノテーション画像'), ('base_images', 'ベース画像')], default='auto', max_length=20, verbose_name='元画像フォルダ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('total_images', models.IntegerField(default=0, verbose_name='総画像数')),
                ('processed_images', models.IntegerField(default=0, verbose_name='処理済み画像数')),
                ('total_crop_areas', models.IntegerField(default=0, verbose_name='総切り取り領域数')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_app_sessions', to='annotator.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '切り取りセッション',
                'verbose_name_plural': '切り取りセッション',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'session_name')},
            },
        ),
        migrations.AddField(
            model_name='cropimage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_images', to='crop_app.cropsession', verbose_name='セッション'),
        ),
        migrations.AlterUniqueTogether(
            name='cropimage',
            unique_together={('session', 'image_name')},
        ),
        migrations.CreateModel(
            name='CropTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('label', models.CharField(max_length=100, verbose_name='ラベル')),
                ('width', models.IntegerField(verbose_name='幅')),
                ('height', models.IntegerField(verbose_name='高さ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_templates', to='annotator.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '切り取りテンプレート',
                'verbose_name_plural': '切り取りテンプレート',
                'ordering': ['template_name'],
                'unique_together': {('project', 'template_name')},
            },
        ),
    ]
