# Generated by Django 5.2.15 on 2026-06-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('workflow_type', models.CharField(choices=[('with_crop', '切り抜きありワークフロー'), ('without_crop', '切り抜きなしワークフロー')], default='with_crop', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ワークフロー設定',
                'verbose_name_plural': 'ワークフロー設定',
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('data_collection', 'データ収集'), ('crop_preparation', '切り抜き準備'), ('annotation', 'アノテーション'), ('training', '学習'), ('production', '員数確認')], max_length=50)),
                ('image_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'タスク進捗',
                'verbose_name_plural': 'タスク進捗',
                'unique_together': {('task_name',)},
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_task', models.CharField(choices=[('data_collection', 'データ収集'), ('crop_preparation', '切り抜き準備'), ('annotation', 'アノテーション'), ('training', '学習'), ('production', '員数確認')], default='data_collection', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='annotator.project')),
                ('workflow_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.workflowsetting')),
            ],
            options={
                'verbose_name': 'プロジェクトワークフロー状態',
                'verbose_name_plural': 'プロジェクトワークフロー状態',
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('data_collection', 'データ収集'), ('crop_preparation', '切り抜き準備'), ('annotation', 'アノテーション'), ('training', '学習'), ('production', '員数確認')], max_length=50)),
                ('image_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='annotator.project')),
            ],
            options={
                'verbose_name': 'プロジェクト別タスク進捗',
                'verbose_name_plural': 'プロジェクト別タスク進捗',
                'unique_together': {('project', 'task_name')},
            },
        ),
    ]
