# Generated by Django 5.2.15 on 2026-06-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_annotated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FF0000', max_length=7)),
                ('is_active', models.BooleanField(default=False, help_text='このラベルがプロジェクト内でアクティブかどうか')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('folder_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('cropped', models.BooleanField(default=False)),
                ('save_path', models.CharField(blank=True, help_text='画像保存先パス', max_length=512, null=True)),
                ('active_yaml_path', models.CharField(default='', help_text='アクティブなYAML設定ファイルのパス', max_length=512)),
                ('active_weight_path', models.CharField(default='', help_text='アクティブな重みファイルのパス', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_center', models.FloatField()),
                ('y_center', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotator.imagefile')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.label')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='annotator.project'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annotator.project'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('project', 'name')},
        ),
    ]
